In [53]:
import torch
import pandas as pd
from model import NeuralNetwork
from torch.utils.data import DataLoader, Dataset

In [39]:
from torchvision import datasets
from torchvision.transforms import ToTensor

training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

In [52]:
training_data.train_labels

/Users/bryanmichalek/Documents/GitHub_Personal/sports_betting_repo/.venv/lib/python3.9/site-packages/torchvision/datasets/mnist.py:65: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")


tensor([9, 0, 0,  ..., 3, 0, 5])

In [28]:
X = torch.rand(128, 20, device='cpu')

In [29]:
X

tensor([[0.9167, 0.7217, 0.4006,  ..., 0.7056, 0.7602, 0.6686],
        [0.0470, 0.1102, 0.9176,  ..., 0.2904, 0.1956, 0.7441],
        [0.0036, 0.7638, 0.4292,  ..., 0.8164, 0.3518, 0.8400],
        ...,
        [0.8844, 0.7043, 0.8252,  ..., 0.9687, 0.5030, 0.6257],
        [0.6411, 0.8181, 0.0613,  ..., 0.1937, 0.1187, 0.8945],
        [0.8158, 0.8218, 0.6172,  ..., 0.2443, 0.4184, 0.8033]])

In [30]:
train_dataloader = DataLoader(X, batch_size=64)

In [31]:
model = NeuralNetwork(n_features=20)

In [33]:
for batch in train_dataloader:
    pred = model(batch)
    print(pred)

tensor([[ 0.1620],
        [ 0.0852],
        [ 0.0765],
        [ 0.0625],
        [ 0.0978],
        [ 0.1248],
        [ 0.1567],
        [ 0.0977],
        [ 0.1411],
        [ 0.1918],
        [ 0.1430],
        [ 0.0652],
        [ 0.1310],
        [ 0.1604],
        [ 0.0734],
        [ 0.2279],
        [ 0.0385],
        [ 0.0802],
        [-0.0145],
        [ 0.1470],
        [ 0.1602],
        [ 0.1827],
        [ 0.1586],
        [ 0.1059],
        [ 0.1859],
        [ 0.1322],
        [ 0.0875],
        [ 0.0714],
        [ 0.1359],
        [ 0.1414],
        [ 0.0430],
        [ 0.1783],
        [ 0.1155],
        [ 0.1231],
        [ 0.1598],
        [ 0.2141],
        [ 0.1715],
        [ 0.1148],
        [ 0.1425],
        [ 0.1479],
        [ 0.1437],
        [ 0.1210],
        [ 0.1364],
        [ 0.0092],
        [ 0.0972],
        [ 0.1406],
        [ 0.1616],
        [ 0.1040],
        [ 0.1583],
        [ 0.1529],
        [ 0.1033],
        [ 0.1597],
        [ 0.

In [54]:
x = Dataset()